// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3y_hQ-89f0EWv8XRpH3Wvat5Cvxvbvr8',
    appId: '1:1060674366308:web:9ff62e3fbc17059cd6e871',
    messagingSenderId: '1060674366308',
    projectId: 'red-line-8eb32',
    authDomain: 'red-line-8eb32.firebaseapp.com',
    storageBucket: 'red-line-8eb32.firebasestorage.app',
    measurementId: 'G-DZ1SMYSCXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbI1FnI5QOuJLXanUaxTunxo3jVq4_S90',
    appId: '1:1060674366308:android:a1d912fa642d93f4d6e871',
    messagingSenderId: '1060674366308',
    projectId: 'red-line-8eb32',
    storageBucket: 'red-line-8eb32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUXegjjSkGlvIfAv6MpXnyZThIaM8LwU',
    appId: '1:1060674366308:ios:e09719b90a9b0c98d6e871',
    messagingSenderId: '1060674366308',
    projectId: 'red-line-8eb32',
    storageBucket: 'red-line-8eb32.firebasestorage.app',
    iosBundleId: 'com.example.redLine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvUXegjjSkGlvIfAv6MpXnyZThIaM8LwU',
    appId: '1:1060674366308:ios:e09719b90a9b0c98d6e871',
    messagingSenderId: '1060674366308',
    projectId: 'red-line-8eb32',
    storageBucket: 'red-line-8eb32.firebasestorage.app',
    iosBundleId: 'com.example.redLine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3y_hQ-89f0EWv8XRpH3Wvat5Cvxvbvr8',
    appId: '1:1060674366308:web:9f0193fd44f0fd20d6e871',
    messagingSenderId: '1060674366308',
    projectId: 'red-line-8eb32',
    authDomain: 'red-line-8eb32.firebaseapp.com',
    storageBucket: 'red-line-8eb32.firebasestorage.app',
    measurementId: 'G-FJV2EJK31L',
  );
}
